---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openshift.muller.dev
  resources:
  - clusterversionprogressinsights
  - updatehealthinsights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openshift.muller.dev
  resources:
  - clusterversionprogressinsights/finalizers
  - updatehealthinsights/finalizers
  verbs:
  - update
- apiGroups:
  - openshift.muller.dev
  resources:
  - clusterversionprogressinsights/status
  - updatehealthinsights/status
  verbs:
  - get
  - patch
  - update
