# This rule is not used by the project openshift-update-experience itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to openshift.muller.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openshift-update-experience
    app.kubernetes.io/managed-by: kustomize
  name: updatehealthinsight-viewer-role
rules:
- apiGroups:
  - openshift.muller.dev
  resources:
  - updatehealthinsights
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openshift.muller.dev
  resources:
  - updatehealthinsights/status
  verbs:
  - get
